# monorepo
packages:
  - apps/*
  - packages/*

# package resolution
nodeLinker: hoisted
patchedDependencies:
  "@expo/cli": patches/@expo__cli.patch
  "@likashefqet/react-native-image-zoom": patches/@likashefqet__react-native-image-zoom.patch
  react-native@0.86.2: patches/react-native@0.86.2.patch
  react-native-image-crop-picker@0.51.1: patches/react-native-image-crop-picker@0.51.1.patch
  react-native-config@1.7.2: patches/react-native-config@1.7.2.patch

# catalog
catalog:
  "@natsuneko-laboratory/catalyst-sdk": 1.0.0-alpha.17
  "@natsuneko-laboratory/fleet-renderer-core": 0.2.0
  "@natsuneko-laboratory/fleet-renderer-react-native": 0.1.0
  "@natsuneko-laboratory/memora": 0.3.0
  "@natsuneko-laboratory/react-native-credential-store": 0.1.0-alpha.2
  "@natsuneko-laboratory/react-native-desktop-navigation": 0.1.0-alpha.18
  "@natsuneko-laboratory/react-native-desktop-window-size": 0.1.2
  "@natsuneko-laboratory/react-native-twitter-text": 0.1.0
  "@natsuneko-laboratory/react-native-webcrypto-digest": 0.2.0
  clsx: 2.1.1
  cn: 0.2.6
  tailwind-merge: 3.6.0
  tailwindcss: 4.3.3
  uniwind: 1.12.0

# security
allowBuilds:
  "@firebase/util": false
  "@sentry/cli": true
  core-js: false
  dtrace-provider: false
  esbuild: false
  msgpackr-extract: false
  protobufjs: false
  unrs-resolver: true

minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - "@natsuneko-laboratory/catalyst-sdk"
  - "@natsuneko-laboratory/fleet-renderer-core"
  - "@natsuneko-laboratory/fleet-renderer-react-native"
  - "@natsuneko-laboratory/memora"
  - "@natsuneko-laboratory/react-native-credential-store"
  - "@natsuneko-laboratory/react-native-desktop-navigation"
  - "@natsuneko-laboratory/react-native-desktop-window-size"
  - "@natsuneko-laboratory/react-native-twitter-text"
  - "@natsuneko-laboratory/react-native-webcrypto-digest"
