packages:
  - catalyst-native
allowBuilds:
  "@firebase/util": false
  "@sentry/cli": true
  core-js: false
  dtrace-provider: false
  esbuild: false
  msgpackr-extract: false
  protobufjs: false
  unrs-resolver: true
minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - '@natsuneko-laboratory/catalyst-sdk'
  - '@natsuneko-laboratory/react-native-twitter-text'
  - '@natsuneko-laboratory/fleet-renderer-core'
  - '@natsuneko-laboratory/fleet-renderer-react-native'
  - '@natsuneko-laboratory/memora'
  - '@natsuneko-laboratory/react-native-webcrypto-digest@0.1.0'
patchedDependencies:
  "@expo/cli": patches/@expo__cli.patch
  "@likashefqet/react-native-image-zoom": patches/@likashefqet__react-native-image-zoom.patch
  '@sentry/react-native@8.21.0': patches/@sentry__react-native@8.21.0.patch
  react-native: patches/react-native.patch
  react-native-image-crop-picker@0.51.1: patches/react-native-image-crop-picker@0.51.1.patch
