name: Publish Android AAB

on:
  # push:
  #   tags:
  #     - "v*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    if: github.repository == 'mika-f/Catalyst-Native'
    name: Build and Publish Android App
    runs-on: ubuntu-latest
    concurrency:
      group: android-build
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: ".node-version"
          registry-url: "https://registry.npmjs.org"

      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          version: "10"

      - name: Setup Expo
        uses: expo/expo-github-action@eab7a230208c952974db8c3245cfd78402c7b385 # 9.0.0
        with:
          expo-version: latest
          eas-version: latest
          packager: pnpm
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Setup Java
        uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Write Environment Values
        run: |
          export json='${{ secrets.GOOGLE_SERVICES_JSON }}'
          echo "EXPO_PUBLIC_CATALYST_FOR_ANDROID_CLIENT_ID=${{ secrets.CATALYST_FOR_ANDROID_CLIENT_ID }}" >> .env
          echo "EXPO_PUBLIC_CATALYST_FOR_ANDROID_CLIENT_SECRET=${{ secrets.CATALYST_FOR_ANDROID_CLIENT_SECRET }}" >> .env
          echo "EXPO_PUBLIC_CATALYST_FOR_IOS_CLIENT_ID=" >> .env
          echo "EXPO_PUBLIC_CATALYST_FOR_IOS_CLIENT_SECRET=" >> .env
          echo "$json" > google-services.json

      - name: Build package
        run: |
          SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }} pnpm run build:android:production --non-interactive --output=./dist/app.aab

      # - name: Publish to EAS
      #   run: |
      #     pnpm run submit:android:production --non-interactive --path ./dist/app.aab
